// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EventComponentController from "../../components/event_component/event_component_controller"
application.register("event-component", EventComponentController)

import ModalComponentController from "../../components/modal_component/modal_component_controller"
application.register("modal-component", ModalComponentController)

// Import view component stimulus controllers
// import "../../components"
