// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import EventComponent__EventComponentController from "./event_component/event_component_controller"
application.register("event-component--event-component", EventComponent__EventComponentController)

import ModalComponent__ModalComponentController from "./modal_component/modal_component_controller"
application.register("modal-component--modal-component", ModalComponent__ModalComponentController)
