// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import EventComponentController from "./event_component/event_component_controller"
application.register("event-component", EventComponentController)

import ModalComponentController from "./modal_component/modal_component_controller"
application.register("modal-component", ModalComponentController)
